- hosts: all
  become: yes
  tasks:
    - name: installed epel-release
      yum:
        name: epel-release
        state: latest
    - name: installed nginx
      yum:
        name: nginx
        state: present
    - name: service start nginx
      service:
        name: nginx
        state: started
